import { z } from "zod";
import { categoryColors } from "../theme";

export type Coordinate = [longitude: number, latitude: number];

export type Station = {
	id: string;
	name: string;
	coordinate: Coordinate;
	isMajor?: boolean;
};

export type RailPath = {
	id: string;
	name: string;
	coordinates: Coordinate[];
};

export type Category =
	| "Express"
	| "Highland"
	| "Commuter"
	| "CrossBorder"
	| "Sleeper";

type CategoryConfig = {
	category: Category;
	label: string;
	color: string;
	shape: "circle" | "diamond" | "square" | "triangle" | "hexagon";
};

export const CATEGORIES: Record<Category, CategoryConfig> = {
	Express: {
		category: "Express",
		label: "Central Belt Express",
		color: categoryColors.Express,
		shape: "circle",
	},
	Highland: {
		category: "Highland",
		label: "Highland & Scenic",
		color: categoryColors.Highland,
		shape: "diamond",
	},
	Commuter: {
		category: "Commuter",
		label: "Suburban / Commuter",
		color: categoryColors.Commuter,
		shape: "square",
	},
	CrossBorder: {
		category: "CrossBorder",
		label: "InterCity / Cross-Border",
		color: categoryColors.CrossBorder,
		shape: "triangle",
	},
	Sleeper: {
		category: "Sleeper",
		label: "Caledonian Sleeper",
		color: categoryColors.Sleeper,
		shape: "hexagon",
	},
};

/**
 * The committed timetable's shape, declared once.
 *
 * `timetable.json` is a generated data file that crosses the same trust boundary
 * as any other untrusted input: it is machine-produced, regenerated by
 * `_getData.ts`, and 325 records deep. It was previously cast to `TrainService[]`
 * at the import site with a bare `as`, so a renamed field or a mistyped category
 * would have reached `resolveServiceAtTime` and the canvas as a type error the
 * compiler could not see. `type TrainService` is now derived from this schema, so
 * the two cannot drift apart.
 *
 * Declared here, beside the types that consume it, rather than at the import site
 * in `store.ts`.
 */
const CoordinateSchema = z.tuple([z.number(), z.number()]);

const ServiceCallSchema = z.object({
	stationId: z.string(),
	/** Minutes from 00:00; `null` where a service does not call, or only passes. */
	arrivalOffset: z.number().nullable(),
	departureOffset: z.number().nullable(),
});

const TrainServiceSchema = z.object({
	id: z.string(),
	serviceNumber: z.string(),
	name: z.string(),
	category: z.enum([
		"Express",
		"Highland",
		"Commuter",
		"CrossBorder",
		"Sleeper",
	]),
	operator: z.string(),
	rollingStock: z.string().optional(),
	pathCoordinates: z.array(CoordinateSchema),
	calls: z.array(ServiceCallSchema),
});

/**
 * Every service in the file.
 *
 * The `id` refinement is the reason this is more than a shape check: `store.ts`
 * resolves a deep link with `allServices.find((s) => s.id === id)`, so a
 * duplicated id would make a shared link silently address the wrong service —
 * `find` resolves to the first and says nothing.
 */
export const TrainServicesSchema = z
	.array(TrainServiceSchema)
	.refine(
		(services) =>
			new Set(services.map((service) => service.id)).size === services.length,
		{
			message:
				"duplicate service id: a deep link would resolve to the wrong service",
		},
	);

export type TrainService = z.infer<typeof TrainServiceSchema>;

type LandmarkKind = "viaduct" | "bridge" | "crossing" | "summit" | "hall";

export type Landmark = {
	id: string;
	name: string;
	coordinate: Coordinate;
	kind: LandmarkKind;
	description: string;
};

export type Loch = {
	id: string;
	name: string;
	coordinates: Coordinate[];
};

export type AppSettings = {
	dayNightCycle: boolean;
	trainHeadlights: boolean;
	showLandmarks: boolean;
	showLochs: boolean;
	congestionHeatmap: boolean;
	cameraFollowTrain: boolean;
	weatherEffects: boolean;
	cityLights: boolean;
	soundEffects: boolean;
};

export const DEFAULT_SETTINGS: AppSettings = {
	dayNightCycle: true,
	trainHeadlights: true,
	showLandmarks: true,
	showLochs: true,
	congestionHeatmap: false,
	cameraFollowTrain: false,
	weatherEffects: true,
	cityLights: true,
	soundEffects: false,
};

export type ViewPreset = "scotland" | "central-belt" | "highlands";

export type Bounds = [west: number, south: number, east: number, north: number];

export const VIEW_BOUNDS: Record<ViewPreset, Bounds> = {
	scotland: [-7.8, 54.7, -1.6, 58.8],
	"central-belt": [-4.9, 55.6, -2.9, 56.2],
	highlands: [-6.5, 56.4, -3.4, 58.7],
};
