on: { workflow_dispatch: {} }

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install && bun run build
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with: { path: ./dist }
      - uses: actions/deploy-pages@v2
